#!/usr/bin/env python3
# from typing import *
from collections import Counter

# def solve(N: int, A: List[int], B: List[int]) -> Tuple[int, int]:
def solve(N, A, B):
    c = 0
    a = Counter(A)
    b = Counter(B)
    
    for i in range(N):
        if A[i] == B[i]:
            c += 1
    d = 0
    for key in a.keys():
        if key in b.keys() and a[key] == b[key]:
            d += 1

    d -= c

    return c, d

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(N):
        B[i] = int(next(tokens))
    assert next(tokens, None) is None

    c, d = solve(N, A, B)
    print(c)
    print(d)


if __name__ == '__main__':
    main()
