#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: List[str], Q: int, x: List[int]) -> Tuple[List[str], List[str], List[str]]:
def solve(N, S, Q, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = next(tokens)
    Q = int(next(tokens))
    x = [None for _ in range(Q)]
    for i in range(Q):
        x[i] = int(next(tokens))
    assert next(tokens, None) is None
    a, e, f = solve(N, S, Q, x)
    for i in range(Q):
        print(a[i], e[i], f[i])


if __name__ == '__main__':
    main()
