#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache

MOD = 998244353


# def solve(N: int, S: List[str]) -> Tuple[int, int, int]:
def solve(N, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    d, e, f = solve(N, S)
    print(d)
    print(e)
    print(f)


if __name__ == '__main__':
    main()
