#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, S: List[str], Q: int, X: List[int], Y: List[int]) -> Tuple[List[str], str]:
def solve(N, M, S, Q, X, Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    Q = int(input())
    X = [None for _ in range(Q)]
    Y = [None for _ in range(Q)]
    for i in range(Q):
        X[i], Y[i] = map(int, input().split())
    c, d = solve(N, M, S, Q, X, Y)
    for i in range(Q):
        print(c[i])
    print(d)


if __name__ == '__main__':
    main()
