#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(N, W, w, v):
    V = sum(v)
    dp = [[float('inf')] * (V+1) for _ in range(N+1)]
    dp[0][0] = 0

    for i in range(N):
        for j in range(V+1):
            if j-v[i] >= 0:
                dp[i+1][j] = min(dp[i][j], dp[i][j-v[i]] + w[i])
            else:
                dp[i+1][j] = dp[i][j]

    for i in range(V, -1, -1):
        if dp[N][i] <= W:
            return i


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, W = map(int, input().split())
    w, v = [], []
    for _ in range(N):
        wi, vi = map(int, input().split())
        w.append(wi)
        v.append(vi)

    print(solve(N, W, w, v))


if __name__ == '__main__':
    main()
