#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


from collections import defaultdict
# def solve(H: int, W: int, S: List[str], T: List[str]) -> str:
def solve(H, W, S, T):
    S_T = defaultdict(int)
    T_T = defaultdict(int)
    for i in range(W):
        s = ''
        t = ''
        for j in range(H):
            if S[j][i] == '#':
                s += '0'
            else:
                s += '1'

            if T[j][i] == '#':
                t += '0'
            else:
                t += '1'
        s = int(s, 2)
        t = int(t, 2)
        S_T[s] += 1
        T_T[t] += 1

    if S_T == T_T:
        return YES
    else:
        return NO
            
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    S = [None for _ in range(H)]
    T = [None for _ in range(H)]
    for i in range(H):
        S[i] = input()
    for i in range(H):
        T[i] = input()
    a = solve(H, W, S, T)
    print(a)


if __name__ == '__main__':
    main()
