#!/usr/bin/env python3
# from typing import *

FIRST = 'First'
SECOND = 'Second'


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    max_len = pow(2, N)
    dp = [[False] * 26 for _ in range(max_len)]

    for i in range(1, max_len):
        for j in range(26):
            for k in range(N):
                if (i >> k) & 1:
                    if str2int(S[k][0]) == j and dp[i-pow(2, k)][str2int(S[k][-1])] == False:
                        dp[i][j] = True
                        break


    for j in range(26):
        if dp[-1][j]:
            return FIRST

    return SECOND


def str2int(s):
    return ord(s) - ord('a')


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
