#!/usr/bin/env python3
# from typing import *


# def solve(S: str, T: str, K: int, C: List[str], A: List[str]) -> int:
def solve(S, T, K, C, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    T = input()
    K = int(input())
    C = [None for _ in range(K)]
    A = [None for _ in range(K)]
    for i in range(K):
        C[i], A[i] = input().split()
    a = solve(S, T, K, C, A)
    print(a)


if __name__ == '__main__':
    main()
