#!/usr/bin/env python3
# from typing import *


# def solve(X: int, Y: int, Z: int) -> int:
def solve(X, Y, Z):
    if 0 < X < Y or Y < X < 0 or Y*X < 0:
        return abs(X)
    elif 0 < Y < Z or Z < Y < 0:
        return -1
    else:
        if X*Z < 0:
            return abs(X) + abs(Z)*2
        else:
            return abs(X)



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, Z = map(int, input().split())
    a = solve(X, Y, Z)
    print(a)


if __name__ == '__main__':
    main()
