#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache

YES = 'Yes'
NO = 'No'

def solve(N, K, S):
    K %= 2*N

    S = list(S)
    S_ = ['A' for _ in range(K)]

    for i in range(min(N, K)):
        if S_[-1-i] == 'A':
            S_[-1-i] = S[i]
        else:
            if S_[-1-i] != S[i]:
                return NO

        if S_[i] == 'A':
            S_[i] = S[-1-i]
        else:
            if S_[i] != S[-1-i]:
                return NO

    for i in range(K):
        if S_[i] == 'A':
            S_[i] = S_[::-1][i]


    S1 = S_ + S
    S2 = S + S_

    if (S1 == S1[::-1]) and (S2 == S2[::-1]):
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    for _ in range(T):
        N, K = map(int, input().split())
        S = input()
        ans = solve(N, K, S)
        print(ans)


if __name__ == '__main__':
    main()
