#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, A: List[int]) -> List[str]:
def solve(N, K, A):
    if K <= N:
        return A[K:] + [0] * K
    else:
        return [0]*N


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    # tokens = iter(sys.stdin.read().split())
    N, K = map(int, input().split())
    A = list(map(int, input().split()))
    ans = solve(N, K, A)
    # print(*[ans[i] for i in range(N)])
    print(*ans)


if __name__ == '__main__':
    main()
