#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, S: List[str]) -> int:
def solve(N, M, S):
    ans = 0
    for i in range(N):
        for j in range(i+1, N):
            flag = False
            for k in range(M):
                if S[i][k] == 'x' and S[j][k] == 'x':
                    flag = True
                    break

            if not flag:
                ans += 1

    return ans




# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, M, S)
    print(a)


if __name__ == '__main__':
    main()
