#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(a: int, b: int, c: List[int], d: List[List[int]]) -> int:
def solve(N, M, C, a):
    ans = 0
    for i in range(1<<M):
        s = set()
        for j in range(M):
            if i & (1<<j):
                for k in a[j]:
                    s.add(k)

        if len(s) == N:
            ans += 1

    return ans



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    C = []
    a = []
    for _ in range(M):
        c = int(input())
        C.append(c)
        a.append(list(map(int, input().split())))

    print(solve(N, M, C, a))


if __name__ == '__main__':
    main()
