#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, E: List[int]) -> int:
def solve(N, K, E):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    E = [None for _ in range(K)]
    for i in range(K):
        E[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, E)
    print(a)


if __name__ == '__main__':
    main()
