#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> str:
def solve(N, S):
    if N == 1:
        return S

    ans = ''
    for i in range(N-1):
        if S[i:i+2] == 'na':
            ans += 'ny'
        else:
            ans += S[i]

    ans += S[-1]
    return ans
        


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
