#!/usr/bin/env python3
# from typing import *


# def solve(N: str, c: List[str]) -> int:
def solve(N, c):
    i = 0
    j = N-1

    ans = 0
    while i < j:
        while i < j and c[i] == 'R':
            i += 1

        while i < j and c[j] == 'W':
            j -= 1

        if i < j:
            ans += 1
            i += 1
            j -= 1

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    c = input()
    a = solve(N, c)
    print(a)


if __name__ == '__main__':
    main()
