#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, S: str) -> int:
def solve(N, X, S):
    s = []
    for i in range(N):
        if S[i] == 'U' and len(s)>0 and s[-1] != 'U':
            s.pop()
        else:
            s.append(S[i])

    ans = X
    for i in range(len(s)):
        if s[i] == 'U':
            ans //= 2
        elif s[i] == 'L':
            ans *= 2
        else:
            ans *= 2
            ans += 1

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    S = input()
    a = solve(N, X, S)
    print(a)


if __name__ == '__main__':
    main()
