#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(N: int, S: List[str]) -> List[str]:
def solve(N, S):
    for i in range(N):
        S[i] = [S[i], i]

    S.sort()

    ans = [0] * N
    for i in range(N-1):
        tmp = 0
        for j in range(len(S[i][0])):
            if S[i][0][j] == S[i+1][0][j]:
                tmp += 1
            else:
                break

        ans[S[i][1]] = max(ans[S[i][1]], tmp)
        ans[S[i+1][1]] = max(ans[S[i+1][1]], tmp)

    return ans



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    ans = solve(N, S)
    for i in range(N):
        print(ans[i])


if __name__ == '__main__':
    main()
