#!/usr/bin/env python3
# from typing import *


# def solve(H: str, W: str, A: List[List[str]], Q: str, a: List[str], b: List[str]) -> List[List[str]]:
def solve(H, W, A, Q, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = next(tokens)
    W = next(tokens)
    A = [[None for _ in range(W)] for _ in range(H)]
    for j in range(H):
        for i in range(W):
            A[j][i] = next(tokens)
    Q = next(tokens)
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    for i in range(Q):
        a[i] = next(tokens)
        b[i] = next(tokens)
    assert next(tokens, None) is None
    B = solve(H, W, A, Q, a, b)
    for j in range(H):
        print(*[B[j][i] for i in range(W)])


if __name__ == '__main__':
    main()
