#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(A: int, B: int, C: int, D: int, E: int) -> int:
def solve(A, B, C, D, E):
    return len(list(set([A, B, C, D, E])))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, D, E = map(int, input().split())
    a = solve(A, B, C, D, E)
    print(a)


if __name__ == '__main__':
    main()
