#!/usr/bin/env python3
# from typing import *


# def solve(H: int, M: int) -> Tuple[int, int]:
def solve(H, M):
    while True:
        h = str(H)
        m = str(M)

        if len(h) == 1:
            h = '0' + h
        if len(m) == 1:
            m = '0' + m

        a = h[0]
        b = m[0]
        c = h[1]
        d = m[1]

        if check(a, b, c, d):
            break

        H, M = plus(H, M)

    return H, M

def check(A, B, C, D):
    H = int(A + B)
    M = int(C + D)

    if 0 <= H <= 23 and 0 <= M <= 59:
        return True
    else:
        return False


def plus(H, M):
    if 0 <= M <= 58:
        M += 1
    else:
        M = 0
        H += 1
        if H == 24:
            H = 0

    return H, M


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, M = map(int, input().split())
    h, m = solve(H, M)
    print(h, m)


if __name__ == '__main__':
    main()
