#!/usr/bin/env python3
# from typing import *

# def solve(S: str) -> int:
def solve(S):
    S = set(list(S))
    if len(S) == 1:
        return 1
    elif len(S) == 2:
        return 3
    else:
        return 6


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
