#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache

MOD = 998244353


# def solve(A: int, B: int, C: int, T: int) -> int:
def solve(A, B, C, T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, T = map(int, input().split())
    a = solve(A, B, C, T)
    print(a)


if __name__ == '__main__':
    main()
