#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache



# def solve(S: List[str]) -> Tuple[int, int, int, int]:
def solve(S):
    N = 10
    A,C = 11, 11
    B, D = -1, -1

    for i in range(N):
        for j in range(N):
            if S[i][j] == '#':
                A = min(A, i+1)
                B = max(B, i+1)
                C = min(C, j+1)
                D = max(D, j+1)

    return A, B, C, D



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = [None for _ in range(10)]
    for i in range(10):
        S[i] = input()
    A, B, C, D = solve(S)
    print(A, B)
    print(C, D)


if __name__ == '__main__':
    main()
