#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(K: int, S: str) -> int:
def solve(K, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    S = input()
    a = solve(K, S)
    print(a)


if __name__ == '__main__':
    main()
