#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(N, A, Q, que):
    for i in range(Q):
        if que[i][0] == 1:
            A[que[i][1]-1] = que[i][2]
        elif que[i][0] == 2:
            print(A[que[i][1]-1])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = list(map(int, input().split()))
    Q = int(input())
    que = [list(map(int, input().split())) for _ in range(Q)]

    solve(N, A, Q, que)

if __name__ == '__main__':
    main()
