#!/usr/bin/env python3
# from typing import *


# def solve(T: str) -> Tuple[int, int]:
def solve(T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    a, b = solve(T)
    print(a)
    print(b)


if __name__ == '__main__':
    main()
