#!/usr/bin/env python3
# from typing import *

# def solve(N: int, K: int, A: List[int]) -> int:
def solve(N, K, A):
    A_n = [A]
    i = 1
    while i*2 < K:
        tmp = []
        for j in range(N):
            tmp.append(A_n[-1][A_n[-1][j]-1])
        A_n.append(tmp)
        i *= 2

    ans = A_n[-1][0]
    K -= i
    while K > 0:
        j = 1
        num = 0
        while j*2 < K:
            j *= 2
            num += 1
        ans = A_n[num][ans-1]
        K -= j

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, A)
    print(a)


if __name__ == '__main__':
    main()
