#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)

YES = 'Yes'
NO = 'No'


# def solve(S: str, T: str) -> Any:
def solve(S, T):
    N = len(T)
    mae = [False] * (N+1)
    usiro = [False] * (N+1)

    mae[0] = True
    usiro[N] = True

    for i in range(N):
        if S[i] == T[i] or S[i] == '?' or T[i] == '?':
            mae[i+1] = True
        else:
            break


    for i in range(N):
        # if S[-N+i] == T[-N+i] or S[-N+i] == '?' or T[-N+i] == '?':
        if S[-1-i] == T[-1-i] or S[-1-i] == '?' or T[-1-i] == '?':
            # usiro[i] = True
            usiro[-2-i] = True
        else:
            break

    for i in range(N+1):
        if mae[i] and usiro[i]:
            print('Yes')
        else:
            print('No')


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    T = input()
    solve(S, T)


if __name__ == '__main__':
    main()
