#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache

def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a % b)

# def solve(a: int, b: List[int], c: List[int], d: List[int]) -> List[str]:
def solve(N, D, K):
    g = gcd(N, D)
    n = N // g

    mod = (K - 1) // n
    ans = mod + (K - 1) * D % N

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    for _ in range(T):
        N, D, K = map(int, input().split())
        ans = solve(N, D, K)
        print(ans)

if __name__ == '__main__':
    main()
