#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, a: List[int], b: List[int]) -> str:
def solve(N, a, b):
    if a[0] == a[1] or a[0] == b[1]:
        v = a[0]
    elif b[0] == a[1] or b[0] == b[1]:
        v = b[0]
    else:
        return NO

    vertexes = []
    for i in range(N-1):
        if a[i] == v:
            vertexes.append(b[i])
        elif b[i] == v:
            vertexes.append(a[i])
        else:
            return NO

    if len(set(vertexes)) == N-1:
        return YES
    else:
        return NO

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    for i in range(N - 1):
        a[i], b[i] = map(int, input().split())
    a1 = solve(N, a, b)
    print(a1)


if __name__ == '__main__':
    main()
