#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(a: int, b: int, c: List[int], d: List[List[int]]) -> str:
def solve(N, M, kx):
    flag = [[False for _ in range(N)] for _ in range(N)]

    for i in range(M):
        for j in range(1, kx[i][0]+1):
            for k in range(1, kx[i][0]+1):
                flag[kx[i][j]-1][kx[i][k]-1] = True
                flag[kx[i][k]-1][kx[i][j]-1] = True

    for i in range(N):
        for j in range(N):
            if flag[i][j] == False:
                return NO


    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    kx = list(list(map(int, input().split())) for _ in range(M))

    print(solve(N, M, kx))

if __name__ == '__main__':
    main()
