#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(S: str) -> int:
def solve(S):
    N = len(S)
    DP = [[0] * 9 for _ in range(N+1)]
    
    for i in range(N):
        DP[i][0] = 1

        if S[i] == 'c':
            j = 1
        elif S[i] == 'h':
            j = 2
        elif S[i] == 'o':
            j = 3
        elif S[i] == 'k':
            j = 4
        elif S[i] == 'u':
            j = 5
        elif S[i] == 'd':
            j = 6
        elif S[i] == 'a':
            j = 7
        elif S[i] == 'i':
            j = 8
        else:
            j = -1

        for k in range(1, 9):
            if k == j:
                DP[i+1][k] = (DP[i][k-1] + DP[i][k]) % MOD
            else:
                DP[i+1][k] = DP[i][k]
    
    # print(DP)
    return DP[N][8]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
