#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(a, b):
    if b >= a:
        return a
    else:
        return a - 1




# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    ans = solve(a, b)

    print(ans)


if __name__ == '__main__':
    main()
