#!/usr/bin/env python3
# from typing import *

from functools import lru_cache
import sys
sys.setrecursionlimit(10**6)

YES = 'Yes'
NO = 'No'

def solve():
    x = set([A[0]])
    y = set([0])

    # x, yのとりうる値の場合の数は高々2*N*Amaxだから、これをセットで保持すれば、O(N*2*N*10)=O(10^7)で解ける
    for i in range(1, N):
        if i % 2 == 0:
            nx = set()
            for sx in x:
                nx.add(sx + A[i])
                nx.add(sx - A[i])
            x = nx
        else:
            ny = set()
            for sy in y:
                ny.add(sy + A[i])
                ny.add(sy - A[i])
            y = ny

    if X in x and Y in y:
        return YES
    else:
        return NO





# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    global N, X, Y, A
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    X = int(next(tokens))
    Y = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    # a = solve(N, x, y, A)
    a = solve()
    print(a)


if __name__ == '__main__':
    main()
