#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(n, x, y):
    zahyo = {}
    for i in range(n):
        zahyo[x[i]+y[i]*5000] = 1

    # X = 5000
    # Y = 5000
    ans = 0

    for i in range(n):
        for j in range(n):
            x1, y1 = x[i], y[i]
            x2, y2 = x[j], y[j]

            nx = x2 - x1
            ny = y2 - y1

            if x2 >= x1 and y2 > y1:
                x3 = x2 - ny
                y3 = y2 + nx

                x4 = x1 - ny
                y4 = y1 + nx

                if x3+y3*5000 in zahyo.keys() and x4+y4*5000 in zahyo.keys():
                    ans = max(ans, (x2-x1)**2 + (y2-y1)**2)

                # if 0 <= x3 <= X and 0 <= y3 <= Y and 0 <= x4 <= X and 0 <= y4 <= Y:
                    # if maze[y3][x3] and maze[y4][x4]:
                        # ans = max(ans, nx**2 + ny**2)

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    x, y = [], []
    for _ in range(n):
        a, b = map(int, input().split())
        x.append(a)
        y.append(b)

    print(solve(n, x, y))


if __name__ == '__main__':
    main()
