#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    boxes = [[False]*26]*len(S)
    from copy import deepcopy
    i = 0

    for s in S:
        if ord('a') <= ord(s) <= ord('z'):
            index = ord(s) - ord('a')
            if boxes[i][index]:
                return NO
            else:
                boxes[i][index] = True
        elif s == '(':
            i += 1
            boxes[i] = deepcopy(boxes[i-1])
        elif s == ')':
            i -= 1

    return YES

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
