#!/usr/bin/env python3
# from typing import *


# def solve(S: int, T: int, M: int, u: List[int], v: List[int]) -> Any:
def solve(S, T, M, u, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S, T, M = map(int, input().split())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = map(int, input().split())
    ans = solve(S, T, M, u, v)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
