#!/usr/bin/env python3
# from typing import *


def list_primes(limit):
    primes = []
    is_prime = [True] * (limit + 1)
    is_prime[0] = False
    is_prime[1] = False

    for p in range (0, limit + 1):
        if not is_prime[p]:
            continue
        if p % 5 == 1:
            primes.append(p)
        for i in range(p*p, limit + 1, p):
            is_prime[i] = False

    return primes

# def solve(n: int, a: List[int]) -> Any:
def solve(N):
    primes = list_primes(55555)

    return primes[:N]



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ans = solve(N)
    print(*ans)

if __name__ == '__main__':
    main()
