#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(N: int, M: int) -> Tuple[List[str], List[str]]:
def solve(N, M):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    L, R = solve(N, M)
    for i in range(N):
        print(L[i], R[i])


if __name__ == '__main__':
    main()
