#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(H: str, W: str, c: List[List[str]]) -> str:
def solve(H, W, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = next(tokens)
    W = next(tokens)
    c = [[None for _ in range(W)] for _ in range(H + W + 2)]
    for j in range(H + 2):
        for i in range(W):
            c[i + j][i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(H, W, c)
    print(a)


if __name__ == '__main__':
    main()
