#!/usr/bin/env python3
# from typing import *


# def solve(X: int, K: int) -> int:
def solve(X, K):
    for i in range(K):
        if X % 10 >= 5:
            X = X // 10 + 1
        else:
            X = X // 10

        if X == 0:
            break

    return X*10**K

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, K = map(int, input().split())
    a = solve(X, K)
    print(a)


if __name__ == '__main__':
    main()
