#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(N: int) -> Any:
def solve(N):
    for B in range(1, 26):
        for A in range(1, 38):
            if pow(3, A) + pow(5, B) == N:
                return A, B

    return [-1]

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ans = solve(N)
    print(*ans)  # TODO: edit here


if __name__ == '__main__':
    main()
