#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> str:
def solve(N, S):
    S = list(S)

    flag = 1
    for i in range(N):
        if S[i] == '"':
            flag *= -1
        elif flag == 1 and S[i] == ',':
            S[i] = '.'

    return ''.join(S)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
