#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, A: List[int]) -> int:
def solve(N, K, A):
    i = K-1
    ans = 0
    while N > 0:
        while A[i] > N:
            i -= 1
        N -= A[i]
        ans += A[i]

        if N <= 0:
            break

        while A[i] > N:
            i -= 1
        N -= A[i]

    return ans
        


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(K)]
    for i in range(K):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, A)
    print(a)


if __name__ == '__main__':
    main()
