#!/usr/bin/env python3
# from typing import *


# def solve(V: int, A: int, B: int, C: int) -> str:
def solve(V, A, B, C):
    S = A+B+C
    V %= S
    if V < A:
        return 'F'
    elif V < A+B:
        return 'M'
    else:
        return 'T'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    V, A, B, C = map(int, input().split())
    a = solve(V, A, B, C)
    print(a)


if __name__ == '__main__':
    main()
