#!/usr/bin/env python3
# from typing import *


# def solve(Y: int) -> int:
def solve(Y):
    if Y % 4 == 0:
        return Y + 2
    elif Y % 4 == 1:
        return Y + 1
    elif Y % 4 == 2:
        return Y
    elif Y % 4 == 3:
        return Y + 3


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Y = int(input())
    a = solve(Y)
    print(a)


if __name__ == '__main__':
    main()
