#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)

MOD = 998244353


# def solve(N: int, M: int, X: int) -> int:
def solve(N, M, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, X = map(int, input().split())
    a = solve(N, M, X)
    print(a)


if __name__ == '__main__':
    main()
