#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    n = len(S)
    for i in range(n-1, -1, -1):
        if S[i] == 'a':
            return i+1

    return -1



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
