#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: int, A: List[int]) -> Tuple[int, int]:
def solve(N, T, A):
    sum_A = sum(A)
    T %= sum_A

    i = 0
    while T > 0:
        T -= A[i]
        i += 1

    return i, T+A[i-1]




# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    T = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    c, d = solve(N, T, A)
    print(c, d)


if __name__ == '__main__':
    main()
