#!/usr/bin/env python3
# from typing import *

# def solve(N: int, M: int, A: List[int], B: List[int]) -> Any:
def solve(N, M, A, B):
    AB = list(zip(A, B))
    ans = [[] for _ in range(N+1)]

    AB.sort(key=lambda x: x[0])
    for i in range(M):
        ans[AB[i][1]].append(AB[i][0])

    AB.sort(key=lambda x: x[1])
    for i in range(M):
        ans[AB[i][0]].append(AB[i][1])

    for i in range(1, N+1):
        n = len(ans[i])
        tmp = [n] + ans[i]
        print(*tmp)



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    for i in range(M):
        A[i], B[i] = map(int, input().split())
    solve(N, M, A, B)


if __name__ == '__main__':
    main()
