#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: List[str], c: List[List[str]], d: str, e: str) -> Tuple[str, List[str]]:
def solve(N, A):
    ans = 0
    for i in range(N):
        if A[i] % 2 != 0:
            ans += 1
    return ans



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    for _ in range(T):
        N = int(input())
        A = list(map(int, input().split()))
        ans = solve(N, A)
        print(ans)


if __name__ == '__main__':
    main()
