#!/usr/bin/env python3
# from typing import *


# def solve(H: str, W: str, S: List[List[str]]) -> int:
def solve(H, W, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = next(tokens)
    W = next(tokens)
    S = [[None for _ in range(W)] for _ in range(H)]
    for j in range(H):
        for i in range(W):
            S[j][i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(H, W, S)
    print(a)


if __name__ == '__main__':
    main()
