#!/usr/bin/env python3
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache

import platform
if platform.python_implementation() == 'PyPy':
    import pypyjit
    pypyjit.set_param('max_unroll_recursion=-1')

YES = 'Yes'
NO = 'No'



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    from collections import defaultdict

    d = defaultdict(int)

    for i in range(Q):
        c, x = map(int, input().split())
        if c == 1:
            d[x] += 1
        elif c == 2:
            d[x] += 2
        else:
            if d[x] >= 2:
                print(YES)
            else:
                print(NO)



if __name__ == '__main__':
    main()
