#!/usr/bin/env python3
# from typing import *
from functools import lru_cache

# def solve(N: int) -> int:
def solve(N):
    return f(N)

@lru_cache(maxsize=None)
def f(n):
    if n == 0:
        return 1

    return f(n//2) + f(n//3)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
