#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, p: List[int]) -> int:
def solve(N, K, p):
    p.sort()
    return sum(p[i] for i in range(K))



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    p = [None for _ in range(N)]
    for i in range(N):
        p[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, p)
    print(a)


if __name__ == '__main__':
    main()
