#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> Tuple[List[str], List[str], str]:
def solve(N, A):
    ans = [0]

    for i in range(N):
        ans.append(ans[A[i]-1] + 1)
        ans.append(ans[A[i]-1] + 1)

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None

    ans = solve(N, A)

    for a in ans:
        print(a)


if __name__ == '__main__':
    main()
