#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(a: int, b: int) -> str:
def solve(a, b):
    if b < a:
        a, b = b, a

    if a*2 == b or a*2 + 1 == b:
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    a1 = solve(a, b)
    print(a1)


if __name__ == '__main__':
    main()
