#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, X: int, A: List[int], B: List[int]) -> str:
def solve(N, X, A, B):
    dp = [[False] * (X+1) for _ in range(N+1)]

    dp[0][0] = True
    for i in range(N):
        for j in range(X+1):
            if dp[i][j] == False:
                continue

            for k in range(B[i]+1):
                if j + A[i] * k > X:
                    break

                dp[i+1][j+A[i]*k] = True


    if dp[N][X] == True:
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    a = solve(N, X, A, B)
    print(a)


if __name__ == '__main__':
    main()
