#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(A, B, C, K):
    max_num = max(A, B, C)
    ans = max_num * 2**K + A + B + C - max_num
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C = map(int, input().split())
    K = int(input())

    ans = solve(A, B, C, K)

    print(ans)


if __name__ == '__main__':
    main()
