#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> int:
def solve(N, S):
    R = []
    G = []
    B = []
    for i in range(N):
        if S[i] == 'R':
            R.append(i)
        elif S[i] == 'G':
            G.append(i)
        else:
            B.append(i)

    ans = len(R)*len(G)*len(B)
    for i in range(N):
        for j in range(i+1, N):
            if j + (j-i) >= N:
                continue
            if S[i] != S[j] and S[j] != S[j+(j-i)] and S[i] != S[j+(j-i)]:
                ans -= 1

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
