#!/usr/bin/env python3
# from typing import *


# def solve(N: str, A: List[List[str]]) -> str:
def solve(N, A):
    flag = False

    for i in range(N):
        for j in range(N):
            if A[i][j] == 'W':
                if A[j][i] != 'L':
                    flag = True
                    break
            elif A[i][j] == 'L':
                if A[j][i] != 'W':
                    flag = True
                    break
            elif A[i][j] == 'D':
                if A[j][i] != 'D':
                    flag = True
                    break

    if flag:
        return 'incorrect'
    else:
        return 'correct'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [list(input()) for _ in range(N)]
    a = solve(N, A)
    print(a)


if __name__ == '__main__':
    main()
