#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(N, ABC):
    dp = [[0] * 3 for _ in range(N+1)]

    for i in range(N):
        for j in range(3):
            dp[i+1][j] = max(dp[i][k] for k in range(3) if k != j) + ABC[i][j]

    return max(dp[N])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ABC = []
    for i in range(N):
        abc = list(map(int, input().split()))
        ABC.append(abc)

    print(solve(N, ABC))


if __name__ == '__main__':
    main()
