#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache


# def solve(N: int) -> str:
def solve(N):
    if N < 16:
        return '0' + str(hex(N)[2:].upper())
    else:
        return str(hex(N)[2:].upper())


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
