#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> int:
def solve(N, A):
    odd_max, odd_max2 = -1, -1
    even_max, even_max2 = -1, -1

    for i in range(N):
        if A[i] % 2 == 0:
            if A[i] > even_max:
                even_max2 = even_max
                even_max = A[i]
            elif A[i] > even_max2:
                even_max2 = A[i]
        else:
            if A[i] > odd_max:
                odd_max2 = odd_max
                odd_max = A[i]
            elif A[i] > odd_max2:
                odd_max2 = A[i]

    ans = -1
    if odd_max >= 0 and odd_max2 >= 0:
        ans = max(ans, odd_max + odd_max2)
    if even_max >= 0 and even_max2 >= 0:
        ans = max(ans, even_max + even_max2)

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A)
    print(a)


if __name__ == '__main__':
    main()
