#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(s: str) -> str:
def solve(s):
    ans = ''
    for i in range(len(s)):
        if s[i] == '0':
            ans += '1'
        else:
            ans += '0'

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    a = solve(s)
    print(a)


if __name__ == '__main__':
    main()
