#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache


# def solve(a: int, b: int, c: int, d: int) -> Tuple[int, str]:
def solve(a, b, c, d):
    return (a+b)*(c-d), 'Takahashi'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c, d = map(int, input().split())
    g, h = solve(a, b, c, d)
    print(g)
    print(h)


if __name__ == '__main__':
    main()
