#!/usr/bin/env python3
# from typing import *

from collections import defaultdict

# def solve(N: int, S: List[str]) -> List[str]:
def solve(N, S):
    d = defaultdict(int)
    ans = []
    for i in range(N):
        if d[S[i]] == 0:
            ans.append(S[i])
        else:
            ans.append(S[i] + '(' + str(d[S[i]]) + ')')
        d[S[i]] += 1

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    ans = solve(N, S)
    for i in range(N):
        print(ans[i])


if __name__ == '__main__':
    main()
