#!/usr/bin/env python3
# from typing import *


# def solve(S: str, T: str) -> int:
def solve(S, T):
    for i in range(len(S)):
        if S[i] != T[i]:
            return i + 1
    return len(S) + 1


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    T = input()
    a = solve(S, T)
    print(a)


if __name__ == '__main__':
    main()
