#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    one = ['H', 'D', 'C', 'S']
    two = ['A' , '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' , 'T' , 'J' , 'Q' , 'K']

    if len(set(S)) != N:
        return NO

    for s in S:
        if s[0] not in one or s[1] not in two:
            return NO

    return YES



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
