#!/usr/bin/env python3
# from typing import *
import numpy as np

# def solve(N: int) -> str:
def solve(N):
    ans = ''
    while N > 0:
        N -= 1
        ans += chr(ord('a') + N % 26)
        N //= 26
    return ans



    # generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
