#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, u: List[int], v: List[int], Q: int, x: List[int], y: List[int]) -> List[str]:
def solve(N, u, v, Q, x, y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    u = [None for _ in range(N)]
    v = [None for _ in range(N)]
    for i in range(N):
        u[i], v[i] = map(int, input().split())
    Q = int(input())
    x = [None for _ in range(Q)]
    y = [None for _ in range(Q)]
    for i in range(Q):
        x[i], y[i] = map(int, input().split())
    a = solve(N, u, v, Q, x, y)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
