#!/usr/bin/env python3
# from typing import *

def xor(a):
    res = 0
    for i in a:
        res ^= i
    return res

# def solve(N: int, a: List[int]) -> List[str]:
def solve(N, a):
    all = xor(a)
    ans = []
    for i in range(N):
        ans.append(all^a[i])
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    b = solve(N, a)
    print(*[b[i] for i in range(N)])


if __name__ == '__main__':
    main()
