#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: List[int]) -> List[str]:
def solve(N, S):
    ans = []
    for i in range(N):
        if i == 0:
            ans.append(S[i])
        else:
            ans.append(S[i] - S[i-1])

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, S)
    # print(*[ans[i] for i in range(N)])
    print(*ans)


if __name__ == '__main__':
    main()
