#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> float:
def solve(N):
    exp = 0

    for i in range(N):
        tmp = 0
        for j in range(1, 7):
            if j <= exp:
                tmp += exp/6
            else:
                tmp += j/6
        exp = tmp

    return exp

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
