#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(N: int, K: int, S: str) -> str:
def solve(N, K, S):
    ans = ''
    n = 0
    for i in range(N):
        if S[i] == 'o' and n < K:
            ans += 'o'
            n += 1
        else:
            ans += 'x'

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    S = input()
    a = solve(N, K, S)
    print(a)


if __name__ == '__main__':
    main()
