#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(n: int, a: List[int]) -> Any:
def solve(H, W, A):
    import numpy as np
    A = np.array(A)
    B = A.T
    return B

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    A = list(list(map(int, input().split())) for _ in range(H))

    ans = solve(H, W, A)

    for a in ans:
        print(*a)


if __name__ == '__main__':
    main()
