#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(N: int, K: int, S: List[str]) -> List[str]:
def solve(N, K, S):
    return sorted(S[:K])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, K, S)
    for i in range(K):
        print(a[i])


if __name__ == '__main__':
    main()
