#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(N, M, B):
    j = (B[0][0]-1) % 7 + 1
    i = (B[0][0]-j) // 7 + 1

    for ii in range(N):
        for jj in range(M):
            if i+ii <= 0 or i+ii >= 10**100+1 or j+jj <= 0 or j+jj >= 8:
                return "No"
            elif B[ii][jj] == (i+ii-1)*7 + (j+jj):
                continue
            else:
                return "No"

    return "Yes"

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    N, M = map(int, input().split())
    B = list(list(map(int, input().split())) for _ in range(N))
    ans = solve(N, M, B)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
