#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(N: int, M: int, A: List[str]) -> int:
def solve(N, M, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = input()
    a = solve(N, M, A)
    print(a)


if __name__ == '__main__':
    main()
