#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> List[str]:
def solve(N, A):
    sorted_A = sorted(list(set(A)))
    from bisect import bisect_right

    n = len(sorted_A)

    ans = [0] * N
    for i in range(N):
        idx = bisect_right(sorted_A, A[i])
        ans[n-idx] += 1

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, A)
    for i in range(N):
        print(ans[i])


if __name__ == '__main__':
    main()
