#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)

YES = 'Yes'
NO = 'No'


# def solve(N: int, K: int, A: List[int], Q: int, l: List[int], r: List[int]) -> List[str]:
def solve(N, K, A, Q, l, r):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    Q = int(next(tokens))
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    for i in range(Q):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, A, Q, l, r)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
