#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> int:
def solve(L1, R1, L2, R2):
    if L1 <= L2:
        if R2 <= R1:
            return R2 - L2
        elif L2 <= R1 <= R2:
            return R1 - L2
        else:
            return 0
    else:
        if R1 <= R2:
            return R1 - L1
        elif L1 <= R2 <= R1:
            return R2 - L1
        else:
            return 0

        # generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    L1, R1, L2, R2 = map(int, input().split())
    a = solve(L1, R1, L2, R2)
    print(a)


if __name__ == '__main__':
    main()
