#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int]) -> str:
def solve(vertexes):
    n = len(vertexes)
    if is_convex(n, vertexes):
        return YES
    else:
        return NO


def cross(x1,y1,x2,y2):
    return x1*y2 - x2*y1

def is_convex(n, vertexes):
    #n多角形の判定
    flg = True #入力された図形が凸ならTrue/凸でないならFalse
    for i in range(n):
        #3頂点を時計回りに参照
        a = vertexes[i%n]
        b = vertexes[(i+1)%n]
        c = vertexes[(i+2)%n]

        #ベクトルab, bcを計算
        vec_ab = [b[0]-a[0], b[1]-a[1]]
        vec_bc = [c[0]-b[0], c[1]-b[1]]

        #外積が
        if cross(*vec_ab, *vec_bc)<0:
            flg = False
            break
    #flg=True の場合は凸多角形、Falseは凸でない多角形
    return flg

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    C = list(map(int, input().split()))
    D = list(map(int, input().split()))
    vertexes = [A,B,C,D]
    a = solve(vertexes)
    print(a)


if __name__ == '__main__':
    main()
