#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(N, M, A, C):
    B = []
    B.append(C[0] // A[0])
    for i in range(1, M+1):
        s = 0
        for j in range(i):
            s += A[i-j] * B[j]
        B.append((C[i]-s)//A[0])

    return B


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    C = list(map(int, input().split()))
    ans = solve(N, M, A, C)
    print(*ans)  # TODO: edit here


if __name__ == '__main__':
    main()
