#!/usr/bin/env python3
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache

import platform
if platform.python_implementation() == 'PyPy':
    import pypyjit
    pypyjit.set_param('max_unroll_recursion=-1')


# def solve(N: int, A: List[int], B: List[int]) -> List[str]:
def solve(N, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N - 1)]
    B = [None for _ in range(N - 1)]
    for i in range(N - 1):
        A[i], B[i] = map(int, input().split())
    ans = solve(N, A, B)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
