#!/usr/bin/env python3
# from typing import *


# def solve(K: int) -> int:
def solve(K):
    see = [False] * K

    a = 0
    for i in range(K):
        a = a*10 + 7
        a %= K

        if see[a]:
            return -1

        see[a] = True
        if a == 0:
            return i+1

    return -1


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    a = solve(K)
    print(a)


if __name__ == '__main__':
    main()
