#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache


def solve(N, Q, L, a, s, t):
    for i in range(Q):
        print(a[s[i]-1][t[i]-1])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    L, a= [], []
    for _ in range(N):
        t = list(map(int, input().split()))
        L.append(t[0])
        a.append(t[1:])

    s, t = [], []
    for _ in range(Q):
        __ = list(map(int, input().split()))
        s.append(__[0])
        t.append(__[1])

    solve(N, Q, L, a, s, t)



if __name__ == '__main__':
    main()
