#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    N = len(S)
    i = 0
    j = N - 1

    while i < N and S[i] == 'a':
        i += 1

    while j >= 0 and S[j] == 'a':
        j -= 1

    if i > j:
        return YES

    if i <= (N - j - 1):
        if S[i:j+1] == S[i:j+1][::-1]:
            return YES
        else:
            return NO
    else:
        return NO




# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
