#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache

MOD = 998244353


# def solve(N: str, X: str, Y: str, c: List[str]) -> int:
def solve(N, X, Y, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    c = [None for _ in range(24)]
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    X = next(tokens)
    Y = next(tokens)
    for i in range(24):
        c[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, X, Y, c)
    print(a)


if __name__ == '__main__':
    main()
