#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, Q: int, A: List[int], B: List[int], L: List[int], R: List[int]) -> Any:
def solve(N, M, Q, A, B, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, Q = map(int, input().split())
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(Q):
        A[i], B[i], L[i], R[i] = map(int, input().split())
    ans = solve(N, M, Q, A, B, L, R)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
