#!/usr/bin/env python3
# from typing import *


# def solve(S: List[str]) -> int:
def solve(S):
    ans = 0
    for x1 in range(9):
        for y1 in range(9):
            for x2 in range(9):
                for y2 in range(9):
                    if x1 <= x2 and y1 < y2 and S[x1][y1] == '#' and S[x2][y2] == '#':
                        x = y2 - y1
                        y = x2 - x1

                        x3 = x2 - x
                        y3 = y2 + y

                        x4 = x1 - x
                        y4 = y1 + y

                        if 0 <= x3 < 9 and 0 <= y3 < 9 and 0 <= x4 < 9 and 0 <= y4 < 9:
                            if S[x3][y3] == '#'  and S[x4][y4] == '#':
                                ans += 1

    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = [None for _ in range(9)]
    for i in range(9):
        S[i] = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
