#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, C: int, D: int) -> str:
def solve(A, B, C, D):
    if A < C or (A==C and B <= D):
        return 'Takahashi'
    else:
        return 'Aoki'

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, D = map(int, input().split())
    a = solve(A, B, C, D)
    print(a)


if __name__ == '__main__':
    main()
