#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: str) -> Any:
def solve(N, T):
    T_reverse = T[::-1]

    for i in range(N):
        S = T[:i] + T[i+N:]
        if S == T_reverse[N-i:2*N-i]:
            print(S)
            print(i)
            return

    print(-1)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    T = input()
    solve(N, T)


if __name__ == '__main__':
    main()
