#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, S: List[int], X: List[int]) -> int:
def solve(N, M, S, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    S = [None for _ in range(N - 1)]
    X = [None for _ in range(M)]
    for i in range(N - 1):
        S[i] = int(next(tokens))
    for i in range(M):
        X[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, S, X)
    print(a)


if __name__ == '__main__':
    main()
