#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    if len(S) != 8:
        return NO
    if not S[1:7].isdigit():
        return NO
    if (ord('A') <= ord(S[0]) <= ord('Z')) and (100000 <= int(S[1:7]) <= 999999) and (ord('A') <= ord(S[7]) <= ord('Z')):
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
