#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, Y: int, U: List[int], V: List[int]) -> Tuple[List[str], List[str]]:
def solve(N, X, Y, U, V):
    from collections import defaultdict
    d = defaultdict(list)
    for i in range(N-1):
        d[U[i]].append(V[i])
        d[V[i]].append(U[i])

    see = [-1 for _ in range(N+1)]
    see[X] = X
    que = [X]

    while see[Y] == -1:
        q = que.pop(0)
        for v in d[q]:
            if see[v] == -1:
                see[v] = q
                que.append(v)

    ans = [Y]
    while ans[-1] != X:
        ans.append(see[ans[-1]])

    return ans[::-1]







# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X, Y = map(int, input().split())
    U = [None for _ in range(N - 1)]
    V = [None for _ in range(N - 1)]
    for i in range(N - 1):
        U[i], V[i] = map(int, input().split())
    result = solve(N, X, Y, U, V)
    print(*result)


if __name__ == '__main__':
    main()
