#!/usr/bin/env python3
# from typing import *


# def solve(W: int) -> Tuple[int, List[int]]:
def solve(W):
    ans = []
    for i in range(1, 100):
        for j in range(3):
            ans.append(i*(10**(j*2)))

    N = len(ans)
    return N, ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W = int(input())
    N, A = solve(W)
    print(N)
    # print(*[A[i] for i in range(N)])
    print(*A)



if __name__ == '__main__':
    main()
