#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(S):
    ans = 0
    c = S[0]
    for s in S:
        if s != c:
            ans += 1
            c = s
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    ans = solve(S)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
