#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, A: List[int]) -> int:
def solve(N, M, A):
    A.sort()
    S = [0]
    for a in A:
        S.append(S[-1] + a)

    i = 0
    j = 1
    res = 0
    first = -1
    while i < N:
        while j < N and (A[j-1] == A[j] or A[j-1] + 1 == A[j]):
            j += 1

        if j == N and (A[-1] == M and A[0] == 0):
            res = max(res, S[j] - S[i] + first)
        else:
            res = max(res, S[j] - S[i])

        if first == -1:
            first = S[j] - S[i]

        i = j
        j += 1

    return S[-1] - res



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    a = solve(N, M, A)
    print(a)


if __name__ == '__main__':
    main()
