#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(N: int, Q: int, X: int, P: List[int], C: List[int], L: List[int], R: List[int]) -> int:
def solve(N, Q, X, P, C, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    X = int(next(tokens))
    P = [None for _ in range(N)]
    C = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(N):
        P[i] = int(next(tokens))
    for i in range(Q):
        C[i] = int(next(tokens))
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, Q, X, P, C, L, R)
    print(a)


if __name__ == '__main__':
    main()
