#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    return 'Four' if 'Y' in S else 'Three'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
