#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, M: int, U: List[int], V: List[int], K: int, x: List[int]) -> str:
def solve(N, M, U, V, K, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    K = int(next(tokens))
    x = [None for _ in range(K)]
    for i in range(K):
        x[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, U, V, K, x)
    print(a)


if __name__ == '__main__':
    main()
