#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache


# def solve(a: str, b: List[str], c: List[str], d: List[str], e: str, f: str, g: str) -> Tuple[str, str, str, List[str]]:
def solve(a, b, c, d, e, f, g):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    d = [None for _ in range(a)]
    for i in range(a):
        b[i], c[i], d[i] = input().split()
    e, f, g = input().split()
    a, b, c, d = solve(a, b, c, d, e, f, g)
    print(a)
    print(b)
    print(c)
    for i in range(c):
        print(d[i])


if __name__ == '__main__':
    main()
