#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(N: int, s: List[str]) -> int:
def solve(N, S):
    for i in range(N):
        S[i] = list(S[i])
        S[i].sort()
        S[i] = ''.join(S[i])

    from collections import Counter
    c = Counter(S)

    ans = 0
    for k, v in c.items():
        ans += v * (v - 1) // 2

    return ans



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    s = [None for _ in range(N)]
    for i in range(N):
        s[i] = input()
    a = solve(N, s)
    print(a)


if __name__ == '__main__':
    main()
