#!/usr/bin/env python3
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache

YES = 'Yes'
NO = 'No'

# def solve(a: int, b: List[int], c: List[List[int]], d: List[List[int]]) -> List[str]:
def solve(N, A, B):
    i = 0
    j = N-1

    while i < j and A[i+1] == A[0]:
        i += 1

    while i < j and A[j] == A[i]:
        j -= 1

    tar = [B[i]]

    i += 1
    while i <= j:
        while i <= j and i + 1 < N and B[i+1] == B[i]:
            i += 1

        tar.append(B[i])

        i += 1

    print(tar)



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    for _ in range(T):
        N = int(input())
        A = list(map(int, input().split()))
        B = list(map(int, input().split()))

        a = solve(N, A, B)
        print(a)

if __name__ == '__main__':
    main()
