#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, c: int, d: int) -> int:
def solve(a, b, c, d):
    return a*d - c*b

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    c, d = map(int, input().split())
    a1 = solve(a, b, c, d)
    print(a1)


if __name__ == '__main__':
    main()
