#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, a: List[int]) -> int:
def solve(N, A):
    ans = 0

    for i in range(1, N+1):
        dp = [[[0] * i for _ in range(N+1)] for _ in range(N+1)]

        dp[1][0][0] = 1
        dp[1][1][A[0] % i] = 1

        for j in range(2, N+1):
            for k in range(j+1):
                for l in range(i):
                    dp[j][k][l] += dp[j-1][k][l]
                    dp[j][k][l] %= MOD
                    if k > 0:
                        dp[j][k][l] += dp[j-1][k-1][(l - A[j-1]) % i]
                        dp[j][k][l] %= MOD

        ans += dp[N][i][0]
        ans %= MOD

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, a)
    print(a1)


if __name__ == '__main__':
    main()
