#!/usr/bin/env python3
# from typing import *


# def solve(H: str, W: str, C: List[List[str]]) -> List[str]:
def solve(H, W, C):
    X = []
    for i in range(W):
        tmp = 0
        for j in range(H):
            if C[j][i] == '#':
                tmp += 1
        X.append(tmp)

    return X


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    H, W = map(int, input().split())
    C = [list(input()) for _ in range(H)]
    X = solve(H, W, C)
    print(*X)


if __name__ == '__main__':
    main()
