#!/usr/bin/env python3
# from typing import *
from collections import defaultdict

YES = 'Yes'
NO = 'No'


# def solve(N: int, X: List[int], Y: List[int], S: str) -> str:
def solve(N, X, Y, S):
    d = defaultdict(list)
    for i in range(N):
        if len(d[Y[i]]) == 0:
            if S[i] == 'R':
                d[Y[i]] = [X[i], -1]
            else:
                d[Y[i]] = [-1, X[i]]
        else:
            if S[i] == 'R':
                if d[Y[i]][0] == -1 or d[Y[i]][0] > X[i]:
                    d[Y[i]][0] = X[i]
            else:
                if d[Y[i]][1] == -1 or d[Y[i]][1] < X[i]:
                    d[Y[i]][1] = X[i]

            if d[Y[i]][0] != -1 and d[Y[i]][1] != -1:
                if d[Y[i]][0] <= d[Y[i]][1]:
                    return YES

    return NO

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    X = [0 for _ in range(N)]
    Y = [0 for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    S = input()
    a = solve(N, X, Y, S)
    print(a)

if __name__ == '__main__':
    main()
