#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(N: int, Q: int, D: List[int], L: List[int], R: List[int]) -> List[str]:
def solve(N, Q, D, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    D = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(Q):
        D[i], L[i], R[i] = map(int, input().split())
    a = solve(N, Q, D, L, R)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
