#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(X: int) -> str:
def solve(X):
    if X >= 30:
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = int(input())
    a = solve(X)
    print(a)


if __name__ == '__main__':
    main()
