#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> Tuple[int, List[int]]:
def solve(N):
    for i in range(N, -1, -1):
        print(i)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    solve(N)


if __name__ == '__main__':
    main()
