#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    ans = 0
    N = 0
    while N < len(S):
        if S[N] != '0':
            ans += 1
            N += 1
        elif (N+1 < len(S)) and (S[N:N+2] == '00'):
            N += 2
            ans += 1
        else:
            N += 1
            ans += 1
        
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
