#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(n: int, a: List[int]) -> int:
def solve(r1, c1, r2, c2):
    p = abs(r2-r1)
    q = abs(c2-c1)

    if p == 0 and q == 0:
        return 0
    elif (p+q<=3) or (p-q==0):
        return 1
    elif (p+q)%2 == 0 or (p+q) <= 6 or abs(p-q) <= 3:
        return 2
    else:
        return 3

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    r1, c1 = map(int, input().split())
    r2, c2 = map(int, input().split())
    a = solve(r1, c1, r2, c2)
    print(a)


if __name__ == '__main__':
    main()
