#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str, T: str) -> int:
def solve(N, S, T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    T = input()
    a = solve(N, S, T)
    print(a)


if __name__ == '__main__':
    main()
