#!/usr/bin/env python3
import sys

sys.setrecursionlimit(10**7)
input = lambda: sys.stdin.readline().rstrip()
from functools import lru_cache

import platform
if platform.python_implementation() == 'PyPy':
    import pypyjit
    pypyjit.set_param('max_unroll_recursion=-1')

YES = 'Yes'
NO = 'No'


# def solve(N: int, S: str) -> str:
def solve(N, S):
    from collections import defaultdict
    d = defaultdict(bool)

    x, y = 0, 0
    d[(x, y)] = True


    for s in S:
        if s == 'L':
            x -= 1
        elif s == 'R':
            x += 1
        elif s == 'U':
            y += 1
        elif s == 'D':
            y -= 1

        if d[(x, y)]:
            return YES

        d[(x, y)] = True

    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
