#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, Q: int, T: List[int], A: List[int], B: List[int]) -> Any:
from collections import defaultdict
def solve(N, Q, T, A, B):
    d = defaultdict(dict)

    for i in range(Q):
        if T[i] == 1:
            d[A[i]][B[i]] = 1
        elif T[i] == 2:
            d[A[i]][B[i]] = 0
        elif T[i] == 3:
            if (B[i] in d[A[i]].keys()) and (A[i] in d[B[i]].keys()):
                if d[A[i]][B[i]] == 1 and d[B[i]][A[i]] == 1:
                    print(YES)
                else:
                    print(NO)
            else:
                print(NO)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    T = [None for _ in range(Q)]
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        T[i], A[i], B[i] = map(int, input().split())
    solve(N, Q, T, A, B)


if __name__ == '__main__':
    main()
