#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int]) -> str:
def solve(S):
    if len(list(set(S))) == 4:
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    S = []
    for i in range(4):
        S.append(input())
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
