#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int) -> Tuple[int, int, int]:
def solve(N, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    d, e, f = solve(N, K)
    print(d, e, f)


if __name__ == '__main__':
    main()
