#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, c: List[int], l: List[int], r: List[int]) -> List[str]:
def solve(N, Q, c, l, r):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    c = [None for _ in range(N)]
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    for i in range(N):
        c[i] = int(next(tokens))
    for i in range(Q):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, Q, c, l, r)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
