#!/usr/bin/env python3
# from typing import *

# def solve(N: int) -> int:
def solve(N):
    ans = ''
    N -= 1
    ans += str(N // 10**5 + 1)*2
    N %= 10**5
    ans += str(N // 10**4)
    N %= 10**4
    ans += str(N // 10**3)
    N %= 10**3
    ans += str(N // 10**2)*2
    N %= 10**2
    tmp = N // 10**1
    ans += str(tmp)
    N %= 10**1
    ans += str(N)
    ans += str(tmp)

    return int(ans)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
