#!/usr/bin/env python3
# from typing import *

# def solve(X: int, A: int, D: int, N: int) -> int:
def solve(X, A, D, N):
    Last = A + (N - 1) * D
    if D == 0:
        return abs(X-A)
    elif (X <= A and D > 0) or (X >= A and D < 0):
        return abs(A-X)
    elif (X >= Last and D > 0) or (X <= Last and D < 0):
        return abs(X-Last)
    else:
        n = int((X-A)/D)
        return min(abs(X - (A + (n+1)*D)), abs(X - (A + n*D)))

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, A, D, N = map(int, input().split())
    a = solve(X, A, D, N)
    print(a)


if __name__ == '__main__':
    main()
