#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(p: int, a: List[int]) -> List[str]:
def solve(p, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    p = int(next(tokens))
    a = [None for _ in range(p)]
    for i in range(p):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    b = solve(p, a)
    print(*[b[i] for i in range(p)])


if __name__ == '__main__':
    main()
