#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Tuple[int, int, int, int, int, int]:
def solve(N):
    n = 2
    while True:
        if N % n == 0:
            rest = N // n
            if rest % n == 0:
                p = n
                q = rest // n
                return p, q
            else:
                q = n
                p = int(rest ** 0.5)
                return p, q
        n += 1

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    for _ in range(T):
        N = int(input())
        p, q = solve(N)
        print(p, q)

if __name__ == '__main__':
    main()
