#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)


# def solve(N: int, A: List[int], B: List[int]) -> List[str]:
def solve(N, A, B):
    for i in range(N):
        print(A[i] + B[i])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    solve(N, A, B)


if __name__ == '__main__':
    main()
