#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(K: int, X: int) -> Any:
def solve(K, X):
    return [i for i in range(X - K + 1, X + K)]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K, X = map(int, input().split())
    ans = solve(K, X)
    print(*ans)  # TODO: edit here


if __name__ == '__main__':
    main()
