#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int) -> float:
def solve(A, B):
    return (A-B)/3 + B

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    a = solve(A, B)
    print(a)


if __name__ == '__main__':
    main()
