#!/usr/bin/env python3
# from typing import *
import sys

sys.setrecursionlimit(10**7)
from functools import lru_cache


# def solve(N: int, M: int, P: int, A: List[int], B: List[int], C: List[int]) -> int:
def solve(N, M, P, A, B, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, P = map(int, input().split())
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    C = [None for _ in range(M)]
    for i in range(M):
        A[i], B[i], C[i] = map(int, input().split())
    a = solve(N, M, P, A, B, C)
    print(a)


if __name__ == '__main__':
    main()
