#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: List[int], X: List[int], Y: List[int], A: List[int]) -> int:
def solve(N, T, X, Y, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    T = [None for _ in range(N)]
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    A = [None for _ in range(N)]
    for i in range(N):
        T[i], X[i], Y[i], A[i] = map(int, input().split())
    a = solve(N, T, X, Y, A)
    print(a)


if __name__ == '__main__':
    main()
