#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(Y: int) -> int:
def solve(Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Y = int(input())
    a = solve(Y)
    print(a)


if __name__ == '__main__':
    main()
