#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int) -> float:
def solve(A, B):
    t = int(pow(2*B/A, -2/3) - 1)

    return min(f(t, A, B), f(t+1, A, B))


def f(t, A, B):
    import math
    return B*t + A/math.sqrt(1+t)



# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    a = solve(A, B)
    print(a)


if __name__ == '__main__':
    main()
